databases:
  - name: micronaut
    databaseName: micronaut_ozey
    user: micronaut_ozey_user

services:
  - type: web
    name: toy_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false